version: '3.8'

services:
  app:
    build: .
    container_name: credit-card-app
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80 && wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  default:
    driver: bridge 